# Generated by Django 5.1 on 2024-09-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('reservar', models.BooleanField(default=False)),
                ('lugar', models.CharField(max_length=100)),
                ('cantidad_reservas', models.IntegerField(default=0)),
            ],
        ),
    ]
