# Generated by Django 5.1.1 on 2025-01-18 21:26

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to=eventos.models.upload_to_establecimiento)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='eventos.evento')),
            ],
        ),
    ]
