# Generated by Django 5.1.1 on 2025-01-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tiene_tipo',
            field=models.BooleanField(default=False, verbose_name='tiene_tipo'),
        ),
    ]
