# Generated by Django 5.1.1 on 2025-01-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_users_tiene_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tipo',
            field=models.CharField(blank=True, choices=[('discotequero', 'Discotequero'), ('fiestero', 'Fiestero')], max_length=20, null=True, verbose_name='tipo'),
        ),
    ]
