# Generated by Django 5.1.1 on 2025-01-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_users_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tipo',
            field=models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('discotequero', 'Discotequero'), ('fiestero', 'Fiestero')], max_length=20, null=True, verbose_name='tipo'),
        ),
    ]
