# Generated by Django 5.1.1 on 2025-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_users_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tiene_tipo',
        ),
        migrations.AlterField(
            model_name='users',
            name='tipo',
            field=models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('discotequero', 'Discotequero'), ('fiestero', 'Fiestero')], default='indefinido', max_length=20, null=True, verbose_name='tipo'),
        ),
    ]
