# Generated by Django 5.1.1 on 2025-02-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('G', 'Genero'), ('A', 'Ambiente'), ('E', 'Especial')], default='G', max_length=1)),
            ],
        ),
    ]
