# Generated by Django 5.1.1 on 2025-02-08 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
        ('fiestero', '0001_initial'),
        ('recomendacion', '0001_load_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.etiqueta')),
            ],
            options={
                'unique_together': {('etiqueta', 'establecimiento')},
            },
        ),
        migrations.CreateModel(
            name='EtiquetasFiestero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.etiqueta')),
                ('fiestero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiestero.fiestero')),
            ],
            options={
                'unique_together': {('etiqueta', 'fiestero')},
            },
        ),
    ]
