# Generated by Django 5.1.1 on 2025-02-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0002_etiquetaestablecimiento_etiquetasfiestero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetaestablecimiento',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='recomendacion.etiqueta'),
        ),
    ]
