# Generated by Django 5.1.1 on 2025-02-08 13:37

import django.core.validators
import django.db.models.deletion
import establecimiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discotequero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='LUNES', max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('departamento', models.CharField(max_length=100, null=True)),
                ('municipio', models.CharField(max_length=100, null=True)),
                ('id_discotequero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='discotequero.discotequero')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('hemisferio_lat', models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur')], max_length=1, null=True)),
                ('hemisferio_lon', models.CharField(blank=True, choices=[('E', 'Este'), ('O', 'Oeste')], max_length=1, null=True)),
                ('establecimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenada', to='establecimiento.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='establecimiento.establecimiento')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.horario')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(null=True, upload_to=establecimiento.models.upload_to_establecimiento)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='establecimiento.establecimiento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='establecimiento',
            constraint=models.UniqueConstraint(fields=('nombre', 'direccion', 'departamento', 'municipio'), name='unique_nombre_direccion_departamento_municipio'),
        ),
        migrations.AddConstraint(
            model_name='establecimiento',
            constraint=models.UniqueConstraint(fields=('nombre', 'id_discotequero'), name='unique_nombre_discotequero'),
        ),
    ]
