# Generated by Django 5.1.1 on 2024-09-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("establecimiento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="establecimiento",
            name="imagen",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
