# Generated by Django 5.1.1 on 2024-09-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discotequero", "0001_initial"),
        ("establecimiento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordenada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                ("direccion", models.CharField(max_length=100)),
                ("este", models.CharField(max_length=100)),
                ("oeste", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dias", models.CharField(max_length=100)),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="ciudad",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="id_discotequero",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="establecimientos",
                to="discotequero.discotequero",
            ),
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="municipio",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="establecimiento",
            name="descripcion",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="establecimiento",
            name="direccion",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="establecimiento",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="establecimiento",
            name="nombre",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="establecimiento",
            name="telefono",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="id_coordenada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="establecimiento.coordenada",
            ),
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="id_horario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="establecimiento.horario",
            ),
        ),
        migrations.AddConstraint(
            model_name="establecimiento",
            constraint=models.UniqueConstraint(
                fields=("nombre", "direccion"), name="unique_nombre_direccion"
            ),
        ),
        migrations.AddConstraint(
            model_name="establecimiento",
            constraint=models.UniqueConstraint(
                fields=("nombre", "id_discotequero"), name="unique_nombre_discotequero"
            ),
        ),
    ]
