# Generated by Django 5.1.1 on 2024-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discotequero", "0001_initial"),
        ("establecimiento", "0002_coordenada_horario_establecimiento_ciudad_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="establecimiento",
            name="unique_nombre_direccion",
        ),
        migrations.RenameField(
            model_name="establecimiento",
            old_name="ciudad",
            new_name="departamento",
        ),
        migrations.AddConstraint(
            model_name="establecimiento",
            constraint=models.UniqueConstraint(
                fields=("nombre", "direccion", "departamento", "municipio"),
                name="unique_nombre_direccion_departamento_municipio",
            ),
        ),
    ]
