# Generated by Django 5.1.1 on 2025-01-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_remove_establecimiento_unique_nombre_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(null=True, upload_to='establecimientos/images/<django.db.models.fields.related.ForeignKey>')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='establecimiento.establecimiento')),
            ],
        ),
    ]
