# Generated by Django 5.1.1 on 2025-01-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_remove_horario_dias_horario_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenada',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='coordenada',
            name='este',
        ),
        migrations.RemoveField(
            model_name='coordenada',
            name='oeste',
        ),
        migrations.AddField(
            model_name='coordenada',
            name='hemisferio_lat',
            field=models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='hemisferio_lon',
            field=models.CharField(blank=True, choices=[('E', 'Este'), ('O', 'Oeste')], max_length=1, null=True),
        ),
    ]
