# Generated by Django 5.1.1 on 2025-01-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0008_remove_coordenada_direccion_remove_coordenada_este_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenada',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='establecimiento.establecimiento'),
        ),
    ]
