# Generated by Django 5.1.1 on 2025-01-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0009_coordenada_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='establecimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenada', to='establecimiento.establecimiento'),
        ),
    ]
