# Generated by Django 5.1.1 on 2025-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0010_alter_coordenada_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenestablecimiento',
            name='imagen_principal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
