# Generated by Django 5.1.1 on 2025-01-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0011_imagenestablecimiento_imagen_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenestablecimiento',
            name='imagen_principal',
        ),
    ]
