# Generated by Django 5.1.1 on 2025-01-21 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0012_remove_imagenestablecimiento_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='latitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='longitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
