# Generated by Django 5.1.1 on 2025-02-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiestero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro'), ('PND', 'Prefiero no decirlo')], max_length=20)),
                ('num_identificacion', models.CharField(max_length=20)),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiestero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, max_length=500, null=True)),
                ('calificacion', models.IntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento')),
                ('fiestero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiestero.fiestero')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fiestero', 'establecimiento'), name='unique_fiestero_establecimiento_feedback')],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='establecimiento.establecimiento')),
                ('fiestero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestero.fiestero')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fiestero', 'establecimiento'), name='unique_fiestero_establecimiento')],
            },
        ),
    ]
