# Generated by Django 5.1 on 2024-09-14 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiestero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad_sexo', models.CharField(max_length=20)),
                ('num_identificacion', models.CharField(max_length=20)),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiestero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='establecimiento.establecimiento')),
                ('fiestero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestero.fiestero')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fiestero', 'establecimiento'), name='unique_fiestero_establecimiento')],
            },
        ),
    ]
