# Generated by Django 5.1.1 on 2024-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiestero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiestero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254)),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("contraseña", models.CharField(max_length=100)),
                ("foto_perfil", models.CharField(max_length=100)),
                ("nombre_completo", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_registro", models.DateField()),
                ("num_identificación", models.CharField(max_length=100)),
                ("pasaporte", models.CharField(max_length=100)),
            ],
        ),
    ]
