# Generated by Django 5.1.1 on 2025-01-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiestero',
            name='identidad_sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20),
        ),
    ]
