# Generated by Django 5.1.1 on 2025-02-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestero', '0002_alter_fiestero_identidad_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiestero',
            name='identidad_sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro'), ('PND', 'Prefiero no decirlo')], max_length=20),
        ),
    ]
