# Generated by Django 5.1.1 on 2024-09-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiestero", "0002_fiestero"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorito",
            name="fiestero",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fiestero.fiestero",
            ),
        ),
    ]
