# Generated by Django 5.1 on 2024-09-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_establecimiento_imagen'),
        ('fiestero', '0003_favorito_fiestero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='establecimiento.establecimiento', unique=True),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='fiestero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestero.fiestero', unique=True),
        ),
    ]
