# Generated by Django 5.1.1 on 2025-02-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0013_alter_coordenada_latitud_alter_coordenada_longitud'),
        ('fiestero', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='establecimiento',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento'),
            preserve_default=False,
        ),
    ]
