# Generated by Django 5.1 on 2024-09-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_establecimiento_imagen'),
        ('fiestero', '0004_alter_favorito_establecimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='establecimiento.establecimiento'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='fiestero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestero.fiestero'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('fiestero', 'establecimiento'), name='unique_fiestero_establecimiento'),
        ),
    ]
