# Generated by Django 5.1 on 2024-09-14 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discotequero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresarial', models.CharField(max_length=100)),
                ('NIT', models.CharField(max_length=20)),
                ('NIT_verificado', models.BooleanField(default=False)),
                ('digito_verificacion', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discotequero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
