# Generated by Django 5.1.1 on 2025-02-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discotequero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresarial', models.CharField(max_length=100)),
                ('NIT', models.CharField(max_length=20)),
                ('NIT_verificado', models.BooleanField(blank=True, default=False, max_length=50, null=True)),
                ('numero_verificacion', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discotequero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
