# Generated by Django 5.1.1 on 2024-10-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discotequero", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discotequero",
            name="digito_verificacion",
            field=models.CharField(max_length=32),
        ),
    ]
