# Generated by Django 5.1.1 on 2025-01-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discotequero', '0002_alter_discotequero_digito_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discotequero',
            name='digito_verificacion',
            field=models.CharField(max_length=10),
        ),
    ]
