# Generated by Django 5.1.1 on 2025-01-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discotequero', '0003_alter_discotequero_digito_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discotequero',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
