# Generated by Django 5.1.1 on 2025-01-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discotequero', '0004_alter_discotequero_digito_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discotequero',
            name='NIT_verificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
