# Generated by Django 5.1.1 on 2025-02-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discotequero', '0005_alter_discotequero_nit_verificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discotequero',
            old_name='digito_verificacion',
            new_name='numero_verificacion',
        ),
    ]
