# Generated by Django 5.1.1 on 2025-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discotequero', '0006_rename_digito_verificacion_discotequero_numero_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discotequero',
            name='NIT_verificado',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discotequero',
            name='numero_verificacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
